#!/bin/bash

exitWithError() {
  local MESSAGE=$1
  echo >&2 "${MESSAGE}";
  exit 1;
}

readBaseVersion() {
  REF=$1
  local BASE_VERSION=$(git show "${REF}:version.txt")
  BASE_VERSION=`echo ${BASE_VERSION} | sed 's/\\r//g'`
  if [[ "${#BASE_VERSION}" -lt 2 ]]; then exitWithError "Could not read base version from version.txt"; fi
  if ! [[ "${BASE_VERSION}" =~ ^[0-9]+\.[0-9]+$ ]]; then exitWithError "The base version is invalid. It doesn't not match <number>.<number>"; fi
  if [[ "${BASE_VERSION}" =~ ^0\.0$ ]]; then exitWithError "The version can not be 0.0"; fi
  if [[ "${BASE_VERSION}" =~ ^0[0-9]+\. ]]; then exitWithError "The major version can not be prefixed with 0"; fi
  if [[ "${BASE_VERSION}" =~ \.0[0-9]+ ]]; then exitWithError "The minor version can not be prefixed with 0"; fi
  
  echo "${BASE_VERSION}"
}

readBaseVersion $1

