name: Repository Dispatch Build

on:
  repository_dispatch:

jobs: 
  repository-dispatch-build:
    name: Repository Dispatch Build
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1

      - name: Checkout triggered sha
        run: git checkout -f "${{  github.event.client_payload.buildSha }}"
    
      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/actions/compute-version@master
        with:
          build-branch: ${{ github.event.client_payload.buildBranch }}
          is-release-flow: false # This line is not needed for docker build. For docker build the value has to be true (which is the default) value

      - name: Gradle Build
        run: gradle build
          
      - name: Unit Test
        run: gradle test

      - name: Gradle Publish
        run: gradle -Pgpr.repo="https://maven.pkg.github.com/ZeroWasteTeam/SampleJavaMavenPackage" -Pgpr.user="${{ github.actor }}" -Pgpr.key="${{ secrets.GITHUB_TOKEN }}" -Pgpr.version="${{ steps.compute-release-version.outputs.version}}" publish
