name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
      - 'release-*'
jobs:

  build-and-test:
    name: Java PR Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Making Custom Scripts As Executable
        run: |
          cd .github/scripts
          echo "::set-env name=PATH::${PATH}:$(pwd)"
          chmod +x *

      - name: For Non Master Branch make sure version file is not modified
        if: github.base_ref != 'master'
        run: ci-assertVersionIsNotModified "origin/${{ github.base_ref }}" "${GITHUB_SHA}"

      - name: For Master Branch verify version modification constraint
        if: github.base_ref == 'master'
        run: ci-assertVersioningRulesFollowed "origin/${{ github.base_ref }}" "${GITHUB_SHA}"

      - name: Extract Base Version
        if: github.base_ref == 'master'
        run: echo "::set-env name=CI_BASE_VERSION::$(ci-readBaseVersion1 origin/${{ github.base_ref }})"

      - name: Extract Modfied Version
        if: github.base_ref == 'master'
        run: echo "::set-env name=CI_MODIFIED_VERSION::$(ci-readBaseVersion1 ${GITHUB_SHA})"

      - name: Verify version modification rules
        if: github.base_ref == 'master'
        run: ci-assertVersionIsEqualOrIncremented "${CI_BASE_VERSION}" "${CI_MODIFIED_VERSION}"
      
      - name: PR - Gradle Build
        run: gradle build
        
      - name: PR - Gradle Test
        run: gradle test
      
