name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
      #- 'rel-*' This line is not needed for Maven build. It is needed for Docker builds (release flow)
jobs:
  pr-build:
    name: PR Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Validating versioning
        uses: ZeroWasteTeam/actions/verify-pr-version@master
        with:
          base-branch:  ${{ github.base_ref }} 
          merged-ref: ${{ github.sha }} 
      
      - name: Enable Scripts
        run: chmod +x ./scripts-*.sh

      - name: Build Script
        run: ./scripts-build.sh ${{ github.actor }} ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Test Script
        run: ./scripts-test.sh

      
