name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
      #- 'rel-*' This line is not needed for Maven build. It is needed for Docker builds (release flow)
jobs:
  pr-build:
    name: PR Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Validating versioning
        uses: ZeroWasteTeam/actions/verify-pr-version@master
        with:
          base-branch:  ${{ github.base_ref }} 
          merged-ref: ${{ github.sha }} 
      
      - name: Gradle Build
        run: gradle build
        
      - name: Gradle Test
        run: gradle test

      
